### ISSUE TITLE
FATA[0000] rpc error: code = Unknown desc = multiple application sources defined: Helm,Plugin

### ISSUE THREAD

**Issue by clcchai** [IBM/argocd-vault-plugin#101]
**Is your feature request related to a problem? Please describe.**
Below is whats working
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-application-name
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    plugin:
      name: argocd-vault-plugin
    repoURL: http://your-repo/
    targetRevision: HEAD
  project: default
```

However, if we want to use source as helm type instead of plain yamls, ie argo application that is of helm source type, and we cant use the plugin together as there is only one type you can use.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .api }}
  project: {{ .argocdProject }}
  source:
    helm:
      valueFiles:
      - values.yaml
    plugin:
      name: argocd-vault-plugin
    path: {{ .path }}
    repoURL: {{ .repo }}
    targetRevision: {{ .targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
```

```
argocd app create argovault-test --config-management-plugin argocd-vault-plugin \
--repo https://github.com/test/test.git \
--path Cluster/test/cluster-resources  \
--dest-server https://kubernetes.default.svc \
--dest-namespace default \
--values value.yaml
FATA[0000] rpc error: code = Unknown desc = multiple application sources defined: Helm,Plugin
```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by werne2j** [comment]
This is not a problem with the plugin itself but instead an issue with how you are trying to combine multiple application sources like the error says. If you are trying to create an app of apps via helm then you would want something like
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .api }}
  project: {{ .argocdProject }}
  source:
    plugin:
      name: argocd-vault-plugin
    path: {{ .path }}
    repoURL: {{ .repo }}
    targetRevision: {{ .targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
```
And then that file would be in your templates folder with your values files having the information for this template. Then to create the apps you would do
```
argocd app create argovault-test \
--repo https://github.com/test/test.git \
--path Cluster/test/cluster-resources  \
--dest-server https://kubernetes.default.svc \
--dest-namespace default \
--values value.yaml
```
So this would create one app `argovault-test` that has multiple apps inside that then use the argocd-vault-plugin. 

Hopefully that helps

**Comment by clcchai** [comment]
hi Jacob,
hmm..
so this part , apps of apps - helm template
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .api }}
  project: {{ .argocdProject }}
  source:
    plugin:
      name: argocd-vault-plugin
    path: {{ .path }}
    repoURL: {{ .repo }}
    targetRevision: {{ .targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
```

where do you define the values.yaml to inform argocd that this is a helm app?

the second part of the above is just the imperative way, so please ignore it

**Comment by clcchai** [comment]
eg my helm values.yaml look like this:
```
  - name: cluster-configuration
    namespace: authentication
    argocdProject: bootstrapping
    repo: https://github.com/test/test.git
    path: Cluster/shdvcl1001/applications/cluster-config
    targetRevision: HEAD
    api: https://kubernetes.default.svc
```

**Comment by werne2j** [comment]
@clcchai In order to do what you want to do you would have a helm chart that has a structure like this:
```
templates/
  application.yaml
Chart.yaml
values.yaml
```
Where `application.yaml` is
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .api }}
  project: {{ .argocdProject }}
  source:
    plugin:
      name: argocd-vault-plugin
    path: {{ .path }}
    repoURL: {{ .repo }}
    targetRevision: {{ .targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
```
and `values.yaml` is 
```
  - name: cluster-configuration
    namespace: authentication
    argocdProject: bootstrapping
    repo: https://github.com/test/test.git
    path: Cluster/clusterA/applications/cluster-config
    targetRevision: HEAD
    api: https://kubernetes.default.svc
```
Then you would create your argocd app of apps from that helm chart. 
These references may help:
https://github.com/argoproj/argocd-example-apps/tree/master/helm-guestbook
https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/#app-of-apps-pattern

But i am going to say that this is not an issue with the plugin and will close this issue

**Comment by ira-gordin-sap** [comment]
Hi @werne2j, I have the same issue. We already use Helm and I am trying to add argocd-vault-plugin. 
Don't we have some simple solution for this issue meanwhile?

**Comment by ira-gordin-sap** [comment]
Hi @clcchai, did you succeed to create the app using both argocd-vault-plugin and helm?

**Comment by werne2j** [comment]
The solution described above or in the docs here (https://ibm.github.io/argocd-vault-plugin/v1.5.0/usage/#with-helm) is going to be the best bet. This is something we do in production and it works pretty well. There isn’t really much more that can be done because of limitations of Argo CD.

This issue https://github.com/argoproj/argo-cd/issues/7623 could make this easier once done but again that is something we can’t control

**Comment by ira-gordin-sap** [comment]
@werne2j may I pass environment to helm here (https://ibm.github.io/argocd-vault-plugin/v1.5.0/usage/#with-helm) ?

**Comment by ira-gordin-sap** [comment]
@werne2j 
Is the following from [plugin](https://ibm.github.io/argocd-vault-plugin/v1.5.0/usage/#with-helm):
Helm args must be defined in the application manifest:
  source:
    path: your-app
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_args
          value: -f values-dev.yaml -f values-dev-tag.yaml
instead the following in Argo CD application with Helm:
  source:
    path: your-app
    helm:
      valueFiles:
      - values-dev.yaml 
      - values-dev-tag.yaml

**Comment by ira-gordin-sap** [comment]
Hi @werne2j,
I applied the solution with (https://ibm.github.io/argocd-vault-plugin/v1.5.0/usage/#with-helm) as you advised.
I had some issue [with missing helm repository](https://github.com/IBM/argocd-vault-plugin/issues/175#issuecomment-977847761).
Currently I have another issue.
One of my applications/charts uses velero chart which have the following job:
```
kind: Job
metadata:
  name: {{ template "velero.fullname" . }}-upgrade-crds
  namespace: {{ .Release.Namespace }}
```
The issue is that when I am using my solution with argocd-vault-plugin-helm, 
this Job is created with argocd namespace and not velero namespace as expected and it causes other issues. 
All other k8s velero objects are created with velero namespace as expected.
Could you please advise?

**Comment by ira-gordin-sap** [comment]
Hi @werne2j, I've fixed this issue by adding ```--namespace=velero``` to ```helm_args``` in the following way:  
```
plugin:
      env:
      - name: helm_args
        value: --namespace=velero -f values.yaml
      name: argocd-vault-plugin-helm
```

Now it looks like works properly but I wonder if all the issues solved.
