### ISSUE TITLE
Kubernetes authorization service account should include permissions for tokenreviews

### ISSUE THREAD

**Issue by rgordill** [IBM/argocd-vault-plugin#102]
**Describe the bug**
When using the kubernetes authorization, the serviceaccount needs tokenreviews for vault to be valid. It is the same as https://github.com/coreos/vault-operator/issues/359.

**To Reproduce**
Using a service account with the vault.

**Expected behavior**
Document that references this requirement.

**Screenshots**
2021-03-24T01:10:42.768Z [ERROR] auth.kubernetes.auth_kubernetes_6370701c: login unauthorized due to: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"tokenreviews.authentication.k8s.io is forbidden: User \"system:serviceaccount:argocd:argocd-server\" cannot create resource \"tokenreviews\" in API group \"authentication.k8s.io\" at the cluster scope","reason":"Forbidden","details":{"group":"authentication.k8s.io","kind":"tokenreviews"},"code":403

**Additional context**
I make it work with the following objects for the previous SA (argocd/default):

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
  name: argocd-repo-server
rules:
- apiGroups:
  - 'authentication.k8s.io'
  resources:
  - 'tokenreviews'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
  name: argocd-repo-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-repo-server
subjects:
- kind: ServiceAccount
  name: default
  namespace: argocd

```
