### ISSUE TITLE
[Issue] Manifest generation error 

### ISSUE THREAD

**Issue by gogovan-vincentngai** [IBM/argocd-vault-plugin#117]
Hi all

I follow the instruction . 

When i deploy a simply like below
```
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp_path: "path/to/mysecret"
type: Opaque
stringData:
  mykey_invault: <mykey_invault>
```

Argo side appear error shows..

rpc error: code = Unknown desc = Manifest generation error (cached): `argocd-vault-plugin generate ./` failed exit status 1: Error: Must provide a supported Vault Type Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD) Must provide a supported Vault Type

What i am missing ? any hints?
