### ISSUE TITLE
How  argocd-vault-plugin-helm support value files ?

### ISSUE THREAD

**Issue by gogovan-vincentngai** [IBM/argocd-vault-plugin#119]
Hi Guys ,

I try to use argocd-vault-plugin , which is works well for single secret file 
However in real , we try use helm to package everything include secret
But then we go to a problem 
This setup in configmap when setup the argocd server
```
configManagementPlugins: |
  - name: argocd-vault-plugin-helm
    generate:
      command: ["sh", "-c"]
      args: ["helm template . > all.yaml && argocd-vault-plugin generate all.yaml"]
```
This wil go without any value file 

```
configManagementPlugins: |
  - name: argocd-vault-plugin-helm
    generate:
      command: ["sh", "-c"]
      args: ["helm template -f value.yaml. > all.yaml && argocd-vault-plugin generate all.yaml"]
```

but if we have multi argocd application they use different value file 
such as 
-f non-production.yaml -f production.yaml

**Comment by werne2j** [comment]
@gogovan-vincentngai We should update the readme but the way to support different values files would be to do something like:
```
    - name: argocd-vault-plugin-helm
      init:
        command: [sh, -c]
        args: ["helm dependency build"] # for dependencies 
      generate:
        command: [sh, -c]
        args: ["helm template --release-name $RELEASE_NAME -f $VALUES_FILE -n $ARGOCD_APP_NAMESPACE . > all.yaml && argocd-vault-plugin generate all.yaml"]
```
and then in your app
```    
plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: RELEASE_NAME
          value: your-release-name
        - name: VALUES_FILE
          value:  non-production.yaml
```
You dont have to do release name but can. And if there are any more flags you want to support you would add them as well
