### ISSUE TITLE
Ignore angle bracket

### ISSUE THREAD

**Issue by antonionappi88** [IBM/argocd-vault-plugin#120]
**Describe the bug**
The plugin tries to convert all the Kubernetes object that can contain `<>`. Not only the ones with the right annotations.

**To Reproduce**
I have a CRD in my YAML.

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: applications.argoproj.io
    app.kubernetes.io/part-of: argocd
  name: applications.argoproj.io
spec:
  group: argoproj.io
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    shortNames:
    - app
    - apps
    singular: application
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.sync.status
      name: Sync Status
      type: string
    - jsonPath: .status.health.status
      name: Health Status
      type: string
    - jsonPath: .status.sync.revision
      name: Revision
      priority: 10
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Application is a <definition> of Application resource.
```
At the end of the YAML there is `<definition>` . The plugin tries to translate it.

**Expected behavior**
I'd expect the script to avoid to parse it. The problem is that the CRD is together with other K8s object that instead contain vault keys.

With stable version the output is:

`URL: GET https://MY_VAULT_URL/v1/customresourcedefinition`

With 1.0.0 version the output is better:

`Error: Replace: could not replace all placeholders in Template: [replaceString: missing Vault value for placeholder definition in string description: Application is a <definition> of Application resource.]`

I'm using the plugin together with kustomize and I need to patch ArgoCD, so I run it like this: 
`XDG_CONFIG_HOME=$PWD && kustomize build --enable_alpha_plugins . > all.yaml && argocd-vault-plugin generate all.yaml -s vault-configuration`

**Comment by werne2j** [comment]
@antonionappi88 you can use the `avp_ignore: "true"` annotation to tell the plugin not to try and process the the file. https://github.com/IBM/argocd-vault-plugin#full-list-of-supported-annotation

For example, you can have a patch:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    avp_ignore: "true"
  name: applications.argoproj.io
  ```
and then include that patch in your `kustomization.yaml`:
```
patchesStrategicMerge:
- application-crd.yaml
```
