### ISSUE TITLE
Support decryption values.yaml

### ISSUE THREAD

**Issue by lcc3108** [IBM/argocd-vault-plugin#124]
My English is not so fluent
**Is your feature request related to a problem? Please describe.**
argocd-vault-plugin don't support decryption values.yaml

**Describe the solution you'd like**
I think support decryption values.yaml  more easier to use

**Describe alternatives you've considered**

**Additional context**

## situation
values.yaml
```yaml
password: <path:secret/data/harbor#password> 
```
templates/secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
data:
  PASSWORD: {{ .Values.password | b64enc | quote }}
```

key : "secret/data/harbor#password"  
value: "password-at-vault"

key and value set at vault 
## if support values.yaml decryption
values.yaml 
decrypt by argocd-vault-plugin
```yaml
password: "password-at-vault"
```
templates/secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
data:
  PASSWORD: "cGFzc3dvcmQtYXQtdmF1bHQ="
  #cGFzc3dvcmQtYXQtdmF1bHQ= equal base64 -d "password-at-vault"
```
but now release
values.yaml
```yaml
password: <path:secret/data/harbor#password>
```
templates/secret.yaml
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
data:
  PASSWORD: PHBhdGg6c2VjcmV0L2RhdGEvaGFyYm9yI3Bhc3N3b3JkPiA=
  #PHBhdGg6c2VjcmV0L2RhdGEvaGFyYm9yI3Bhc3N3b3JkPiA= equal base64 -d "<path:secret/data/harbor#password> "
```
---
It is difficult to change many files under the above circumstances.

**Comment by werne2j** [comment]
> apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
type: Opaque
data:
  PASSWORD: {{ .Values.password | b64enc | quote }}

Do you have control of this secret? If so, you can just remove the ` | b64enc | quote` and either use the `base64encode` modifier we provide of just input a bas64d value in vault.

**Comment by lcc3108** [comment]
It is also possible to change the Helm template.

![image](https://user-images.githubusercontent.com/38449269/118350070-bc5b8f80-b58f-11eb-9b34-05c50090cbcd.png)
but, I have many Helm Charts
Changing multiple Helm templates can also cause human error.
In my humble opinion, it would be good if you could support the method with fewer side effects and changes.

**Comment by llavaud** [comment]
I am facing the same problem and it would great to have this feature.
We use lots of upstream Helm charts and we can't control how they write their charts and often they take the secret value and base64 it...
Before trying your plugin we have used the Banzai mutating webhook and they do something similar for Secret, they decode the value and search for the interpolation pattern.
This is the last feature we are missing before we can migrate to this plugin ! ;)

**Comment by teejaded** [comment]
I'll take a look today and see if I can get something together.  I made a tool that lets you use helm applications with this tool, and it would be useful to have this feature.  Hopefully we can get it into 1.1.0

**Comment by teejaded** [comment]
Oops I found an issue with the feature I implemented while I was converting some apps over to use it.

Consider the following secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPTxwYXRoOnNlY3JldC9hd3MjYWNjZXNzX2tleV9pZD4KYXdzX3NlY3JldF9hY2Nlc3Nfa2V5PTxwYXRoOnNlY3JldC9hd3Mjc2VjcmV0X2FjY2Vzc19rZXlfaWQ+
```

If we base64 decode the credentials we get this:

```ini
[default]
aws_access_key_id=<path:secret/aws#access_key_id>
aws_secret_access_key=<path:secret/aws#secret_access_key_id>
```

Adding modifiers to the placeholders won't let us base64 the entire thing again.  I think the secret replacement needs to implicitly re-base64 a value that it has decoded.

**Comment by werne2j** [comment]
@teejaded Yeah, it seems like the modifiers are no longer working in this scenario..
```
apiVersion: v1
kind: Secret
metadata:
  name: example
  annotations:
    avp.kubernetes.io/path: some/path
data:
  sample-secret: PHB1bGxfc2VjcmV0IHwgYmFzZTY0ZW5jb2RlPg==
type: Opaque
```

Where `PHB1bGxfc2VjcmV0IHwgYmFzZTY0ZW5jb2RlPg==` is `<pull_secret | base64encode>`

And the output is
```
apiVersion: v1
kind: Secret
metadata:
  name: example
  annotations:
    avp.kubernetes.io/path: some/path
data:
  sample-secret: plain-text-secret
type: Opaque
```
Do you want to work on a fix for this? I will reopen the issue

**Comment by werne2j** [comment]
@teejaded actually.. i take that back. The modifier is working. So i am a little confused on what you are referring to as not working? We decided that the plugin is not suppose to base64 a value unless the modifier is used. If someone wants a base64 value injected, they would put it into Vault that way

**Comment by teejaded** [comment]
It only works in the case where the placeholder makes up the entire value.  If I take my example value and add modifiers:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  avp.kubernetes.io/path: some/path
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPTxwYXRoOnNlY3JldC9hd3MjYWNjZXNzX2tleV9pZCB8IGJhc2U2NGVuY29kZT4KYXdzX3NlY3JldF9hY2Nlc3Nfa2V5PTxwYXRoOnNlY3JldC9hd3Mjc2VjcmV0X2FjY2Vzc19rZXlfaWQgfCBiYXNlNjRlbmNvZGU+
```

When you decode `data.credentials` you get:

```ini
[default]
aws_access_key_id=<path:secret/aws#access_key_id | base64encode>
aws_secret_access_key=<path:secret/aws#secret_access_key_id | base64encode>
```

And after AVP you end up with this invalid secret:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  avp.kubernetes.io/path: some/path
type: Opaque
data:
  credentials: |-
    [default]
    aws_access_key_id=dGVzdF9rZXk=
    aws_secret_access_key=dGVzdF9rZXlfc2VjcmV0
```
