### ISSUE TITLE
Using with ArgoCD Declaritive Setup

### ISSUE THREAD

**Issue by jhoover4** [IBM/argocd-vault-plugin#127]
Hello,

Great project! The isn't an issue persae, but more of a general question.

I've been going through the setup, but I'm trying to use this for the initial bootstrapping of Argo itself as described here: https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/. Would the plugin work in that case? Or is it a chicken and egg issue? There doesn't seem to be any substitution happening currently.

For example I'm trying to use it for creating a Secret like this:

```
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  oidc.auth0.clientSecret: <path:foo>
  sshPrivateKey: <path:foo>
  ```
  
Does this Secret need to be applied last? Or will it just not work in this case?

Thank you!
