### ISSUE TITLE
Specify value file at runtime

### ISSUE THREAD

**Issue by Yapcheekian** [IBM/argocd-vault-plugin#140]
**Is your feature request related to a problem? Please describe.**
Extending to issue https://github.com/IBM/argocd-vault-plugin/issues/119 , is there a way to specify which value file to use when trying to create an application in argocd. For example, app A and app B share a same chart but they have different value file.
```
    - name: argocd-vault-plugin-helm
      init:
        command: [sh, -c]
        args: ["helm dependency build"] # for dependencies 
      generate:
        command: [sh, -c]
        args: ["helm template --release-name $RELEASE_NAME -f $VALUES_FILE -n $ARGOCD_APP_NAMESPACE . > all.yaml && argocd-vault-plugin generate all.yaml"]
```
```
plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: RELEASE_NAME
          value: your-release-name
        - name: VALUES_FILE
          value:  non-production.yaml
```
This solution doesn't quite work because I have 15 different apps sharing same chart but all of them have its own value file.
It will be good if I can specify value file to use inside `application.yaml` .
