### ISSUE TITLE
Regex failed with multiple placeholder on same line

### ISSUE THREAD

**Issue by llavaud** [IBM/argocd-vault-plugin#144]
**Describe the bug**
Regex for matching placeholder failed with multiple placeholder on the same line

**To Reproduce**
```
cat <<EOF > pod.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
  - image: foo
    name: foo
    env:
    - name: foo
      value: "<path:mypath#secret1>,<path:mypath#secret2>"
EOF

cat pod.yaml | argocd-vault-plugin generate -
```
AVP will search for a secret with the following path: `mypath#secret1>,<path:mypath`

**Expected behavior**
Search and interpolate the 2 different secrets
