### ISSUE TITLE
Lack of permission scopes for production setup, everyone creating a secret can create any secret in vault

### ISSUE THREAD

**Issue by ksiadz** [IBM/argocd-vault-plugin#153]
**Describe the bug**
There are no permissions scopes in Argo using one single k8s SA or one single AppRole. Meaning that even if you have proper Vault policies with scopes the ArgoCD plugin is still using one Vault Role which forces a practice of one role, assuming most people use Argo to deploy apps of multiple teams, one bad actor in any team can ask to create a secret in his k8s namespace which would be a security issue.

I would expect something like vault-agent which assumes different k8s SA to access different secrets and sends SA_name and NS_name to the vault which does policy check based on those.

Something like
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  namespace: <k8s-namespace in which allowed SA is based>
  annotations:
    avp.kubernetes.io/path: "path/to/secret"
    avp.kubernetes.io/sa-in-use: "sa-name"
type: Opaque
data:
  password: <password-vault-key>

```

I would also expect either Argo Application /ApplicationSet blocking deploying a secret in a namespace that is not a destination namespace in Argo App yaml or some other mechanism blocking unwanted secrets escalation.

**Comment by werne2j** [comment]
Hi @ksiadz, thanks for the issue. After looking into this a workaround that can be done to help improve security. The first thing is that you can take advantage of the Argo CD Application YAML to specify environment variables. This way you can define different AppRole or K8s SA. So you would be able to do:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: some-resource
  namespace: some-ns
spec:
  destination:
    namespace: dest-ns
    name: server-name
  source:
    path: some/path
    repoURL: https://github.com/some/repo
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_AUTH_TYPE
           value: approle
        - name: AVP_ROLE_ID
           value: some-approle-id
        - name: AVP_SECRET_ID
           value: some-secret-id
  project: default
```

This would allow you to specify different role/secrets for each application. That way you dont have to have one app role that can access all secrets. 

> I would also expect either Argo Application /ApplicationSet blocking deploying a secret in a namespace that is not a destination namespace in Argo App yaml or some other mechanism blocking unwanted secrets escalation or actually build-in a way to use vault checks.

Maybe i am misunderstanding but this is already possible via Argo CD projects  https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#projects
