### ISSUE TITLE
Add helm arguments use case in documentation

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [IBM/argocd-vault-plugin#166]
**Is your feature request related to a problem? Please describe.**

I am using the suggested argocd-vault-plugin-helm config : 
``` 
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
    - name: argocd-vault-plugin-helm
      generate:
        command: ["sh", "-c"]
        args: ["helm ${helm_args} template . > all.yaml && argocd-vault-plugin generate all.yaml"]
    - name: argocd-vault-plugin-kustomize
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . > all.yaml && argocd-vault-plugin generate all.yaml"]
```
In argocd application manifest you can define additional [configs](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml#L21) for helm :  
``` 
    helm:
      # Extra parameters to set (same as setting through values.yaml, but these take precedence)
      parameters:
      - name: "nginx-ingress.controller.service.annotations.external-dns\\.alpha\\.kubernetes\\.io/hostname"
        value: mydomain.example.com
      - name: "ingress.annotations.kubernetes\\.io/tls-acme"
        value: "true"
        forceString: true # ensures that value is treated as a string

      # Release name override (defaults to application name)
      releaseName: guestbook

      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      valueFiles:
      - values-prod.yaml
      ....

``` 
Using argocd-vault-plugin, this helm config is not possible.

As a workaround I used this config:

``` 
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
    - name: argocd-vault-plugin-helm
      generate:
        command: ["sh", "-c"]
        args: ["helm ${helm_args} template . > all.yaml && argocd-vault-plugin generate all.yaml"]
    - name: argocd-vault-plugin-kustomize
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . > all.yaml && argocd-vault-plugin generate all.yaml"]
``` 
argocd application manifest:

``` 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollouts-demo-dev
  namespace: argo-cd
  labels:
    environment: dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://mycluster.info
    namespace: dev
  project: argo-rollouts-demo
  source:
    path: config/helm/rollouts-demo
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_args
          value: -f values-dev.yaml -f values-dev-tag.yaml
    repoURL: https://github.com/mytheresa/argo-rollouts-demo.git
    targetRevision: HEAD

``` 
Maybe this could be added to the documentation, or maybe there is a better way to handle this.
