### ISSUE TITLE
allow also <path:/...> into key 

### ISSUE THREAD

**Issue by obeyler** [IBM/argocd-vault-plugin#171]
**Is your feature request related to a problem? Please describe.**
in some product (such by example argocd :-) ) we need to build key into yaml file.
By example the configmap to provide the certificate looks like: 

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-tls-certs-cm
    app.kubernetes.io/part-of: argocd
    avp.kubernetes.io/kv-version: "2"
  name: argocd-tls-certs-cm
data:
  gitlab.mydomain-name.com: |-
   <path:kv/data/global#admin-ca>
```
I put the certificate into a vault by I also want to put the key:  `mydomain-name.com`

**Describe the solution you'd like**
I would like to do this:

```
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-tls-certs-cm
    app.kubernetes.io/part-of: argocd
    avp.kubernetes.io/kv-version: "2"
  name: argocd-tls-certs-cm
data:
  gitlab.<path:kv/data/global#admin-domain>: |-
   <path:kv/data/global#admin-ca>
```
