### ISSUE TITLE
Helm with dependency fails

### ISSUE THREAD

**Issue by omegion** [IBM/argocd-vault-plugin#175]
**Describe the bug**
It seems if the Helm chart has a dependency, it fails that the repository is not found.

```
rpc error: code = Unknown desc = `sh -c helm dependency build` failed exit status 1: Error: no repository definition for https://charts.omegion.dev. Please add the missing repos via 'helm repo add'
```

**To Reproduce**
```
      configManagementPlugins: |-
        - name: argocd-vault-plugin-with-helm
          init:
            command: [sh, -c]
            args: ["helm dependency build"]
          generate:
            command: ["sh", "-c"]
            args: ["helm template $ARGOCD_APP_NAME . > all.yaml && argocd-vault-plugin generate all.yaml -c /etc/config/vault-config.yaml"]
```

**Comment by omegion** [comment]
Okay, it seems I had to add the dependency repositories and restart the repo-server. It does work now.

**Comment by omegion** [comment]
Heck, I forgot to add `plugin` back to Application. Now I can see the error:

```
rpc error: code = Unknown desc = `sh -c helm dependency build` failed exit status 1: Error: no repository definition for https://charts.omegion.dev. Please add the missing repos via 'helm repo add'
```

**Comment by werne2j** [comment]
Seems like this may be a workaround.. `Instead, you can add those repos in your init script.`. Something like `helm repo add https://charts.omegion.dev && helm dependency build`. You could also vendor the helm dependencies.

**Comment by omegion** [comment]
Vendoring the dependencies is the way to go for me. Adding all repos in the `init` does not make sense. Thanks.

**Comment by tuananh** [comment]
> Vendoring the dependencies is the way to go for me. Adding all repos in the `init` does not make sense. Thanks.

What do you mean by vendoring the dependencies?

**Comment by omegion** [comment]
@tuananh https://helm.sh/docs/helm/helm_dependency_update/
You can sync your dependencies on your repo, then ArgoCD will use them rather than fetching from remote.

**Comment by tuananh** [comment]
@omegion thanks. when i do `helm dependency update`, it will download the chart to `charts` folder. so i will use that instead right?

do i need to update `configManagementPlugins` init and generate steps?

**Comment by omegion** [comment]
@tuananh you do not have to change.

**Comment by tuananh** [comment]
Because in `Chart.yaml`, it still has the url to the private repo? that remains unchanged and `charts` folder will take priority over that?

**Comment by omegion** [comment]
Indeed, you can read more here: https://helm.sh/docs/helm/helm_dependency/

**Comment by tuananh** [comment]
Thank you. I got it working now.

**Comment by rwong2888** [comment]
I am running into the same problem... what do your plugin config and app look like @omegion , @tuananh ?

I have below.... I tried changing the args for init to `helm dependency update` with and without `helm repo add`...

plugin
```
  configManagementPlugins: |-
    - name: argocd-vault-plugin-helm
      init:
        command: ["sh", "-c"]
        args: ["helm repo add ${helm_dependency_name} ${helm_dependency_repo} --debug && helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template ${helm_args} . > all.yaml && argocd-vault-plugin generate all.yaml"]
```

Application
```
spec:
  source:
    plugin:
      name: argocd-vault-plugin-helm
      env:
      - name: AVP_K8S_ROLE
        value: xxx
      - name: AVP_TYPE
        value: vault
      - name: AVP_AUTH_TYPE
        value: k8s
      - name: AVP_K8S_MOUNT_PATH
        value: xxx
      - name: VAULT_ADDR
        value: 'xxx'
      - name: helm_args
        value: -f values.yaml
      - name: helm_dependency_name
        value: jetstack
      - name: helm_dependency_repo
        value: 'https://charts.jetstack.io'
```

Getting below error now:
```
rpc error: code = Unknown desc = `sh -c helm repo add ${helm_dependency_name} ${helm_dependency_repo} --debug && helm dependency build` failed exit status 1: Error: looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached: open /home/argocd/.cache/helm/repository/jetstack-index.yaml: read-only file system helm.go:81: [debug] open /home/argocd/.cache/helm/repository/jetstack-index.yaml: read-only file system looks like "https://charts.jetstack.io" is not a valid chart repository or cannot be reached main.(*repoAddOptions).run helm.sh/helm/v3/cmd/helm/repo_add.go:184 main.newRepoAddCmd.func1 helm.sh/helm/v3/cmd/helm/repo_add.go:80 github.com/spf13/cobra.(*Command).execute github.com/spf13/cobra@v1.1.3/command.go:852 github.com/spf13/cobra.(*Command).ExecuteC github.com/spf13/cobra@v1.1.3/command.go:960 github.com/spf13/cobra.(*Command).Execute github.com/spf13/cobra@v1.1.3/command.go:897 main.main helm.sh/helm/v3/cmd/helm/helm.go:80 runtime.main runtime/proc.go:225 runtime.goexit runtime/asm_amd64.s:1371
```

**Comment by rwong2888** [comment]
It's read only filesystem issue introduced in argocd 2.1

https://github.com/argoproj/argo-cd/issues/7144

**Comment by ira-gordin-sap** [comment]
> Seems like this may be a workaround.. `Instead, you can add those repos in your init script.`. Something like `helm repo add https://charts.omegion.dev && helm dependency build`. You could also vendor the helm dependencies.

Hi @werne2j, I had the same issue and fixed it by adding the env variables helm_dependency_name/repo/user/password to my argocd-vault-plugin-credentials (inspired by @rwong2888🧡🙏🏻). 
Maybe this a good idea to add [@rwong2888's solution above](https://github.com/IBM/argocd-vault-plugin/issues/175#issuecomment-912071431) and my solution into [argocd-vault-plugin documentation](https://ibm.github.io/argocd-vault-plugin)?

**Comment by adabuleanu** [comment]
> @tuananh https://helm.sh/docs/helm/helm_dependency_update/ You can sync your dependencies on your repo, then ArgoCD will use them rather than fetching from remote.

Even with the chart archive containing the sub-charts I still get the same error. I am pulling the upstream chart together with its dependencies inside a private helm repo and using that in my ArgoCD app. Is there something I am missing? Can someone explain why is ArgoCD not able to view the local sub-charts when using argocd-vault-plugin-helm?

**Comment by adabuleanu** [comment]
The issue looks more related to helm: https://github.com/helm/helm/issues/8036

**Comment by olegeech-me** [comment]
ok, folks, maybe dump question, but how would I know which repo I need to install if I can have avp with absolutely random helm charts?

**Comment by olegeech-me** [comment]
currently I'm trying to migrate to sidecar configuration with avp, and it used to work (repo dependencies ) by itself when I was using argocd-cm ConfigMap previously like this:
```
configManagementPlugins: |-
- name: argocd-vault-plugin
  generate:
    command: ["argocd-vault-plugin"]
    args: ["generate", "./"]
- name: argocd-vault-plugin-helm
  init:
    command: [sh, -c]
    args: ["env > /tmp/plugin_env; helm dependency build"]
  generate:
    command: ["bash", "-c"]
    args: ['helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE -f ${ARGOCD_ENV_HELM_VALUES_FILE:-values.yaml} -f <(echo "$ARGOCD_ENV_HELM_VALUES") . | tee /tmp/last_manifest.yaml | argocd-vault-plugin generate -']
```

**Comment by olegeech-me** [comment]
FYI: was able to make it working with sidecars by injecting this into the side car:
```
                env:
                  - name: HELM_CACHE_HOME
                    value: /helm-working-dir
                  - name: HELM_CONFIG_HOME
                    value: /helm-working-dir
                  - name: HELM_DATA_HOME
                    value: /helm-working-dir
```
and also mounting `helm-working-dir` volume (from argocd-cmp-server container) into sidecar plugin container.
`helm dependency update` solves everything and I don't have to add repos during init stage.

**Comment by dnnnvx** [comment]
Thanks @olegeech-me your solution saved me other tons of hours trying to make it work. Hope it will be documented

**Comment by kxs-sindrakumar** [comment]
@olegeech-me did you still have env > /tmp/plugin_env in your command?

**Comment by PrayagS** [comment]
I spend quite some time trying to set this plugin up for applications with dependencies. Turns out it's easier to not go through all these hoops to restore default behavior and instead use https://github.com/crumbhole/argocd-lovely-plugin which has a nice feature to chain plugins.

There's also a build of it which has this vault plugin bundled and ready to use out of the box.

**Comment by lauer** [comment]
I encountered many dead ends while troubleshooting this issue, including this bug report. I just wanted to share that, in my case, the problem was caused by the resource limits set on the repository resource.

Updating the resource limits to:

```yaml
- resources:
    limits:
      cpu: '2'
      memory: 1Gi
```

resolved the strange behavior I was experiencing when ArgoCD tried to run `helm dependency update` and `helm repo add`.

I hope this helps others facing similar issues!
