### ISSUE TITLE
How to use argocd-vault-plugin for values.yaml

### ISSUE THREAD

**Issue by gris-gris** [IBM/argocd-vault-plugin#178]
**Is your feature request related to a problem? Please describe.**
I have separate values.yaml for all my application deployed with ArgoCD Helm, and currently I'm using argocd-vault-plugin only for static Secrets.

Is it possible to use "<path:secret/location/in#vault>" within Values.yaml for separate applications and how to implement it?

Current argoproj setup application source for deployments:
```
  source:
    chart: {{ default $appValues.name $appValues.chartName }}
    repoURL: {{ $appValues.repoURL }}
    targetRevision: {{ default ( index $.Values.defaults.chartVersions $appValues.name) $appValues.targetRevision }}
    helm:
      version: v3
      releaseName: {{ $appValues.name }}
      valueFiles:
        - values.yaml
      values: |
        {{- toYaml (mergeOverwrite ((index $.Values.defaults $appValues.name | default dict)) ($.Files.Get (printf "values/%s.yaml" $appValues.name) | fromYaml) | default dict) | nindent 8 }}
```
Current argoproj setup for secrets:
```
  source:
    plugin:
      name: argocd-vault-plugin
    path: {{ .Values.global.path }}/secrets/ # parsing all yaml files in directory
    repoURL: {{ .Values.global.repoURL }}
    targetRevision: {{ .Values.global.secrets.targetRevision }}
```

**Describe the solution you'd like**
I'd like to use links to vault secrets in Values.yaml for each application, like that:
```
# content of "argocd/environments/prod/values/superservice.yaml"
secrets:
  apiToken: <path:application/superservice#apiToken>
``` 

The goal: 
All Values.yaml rendering and using Vault secrets when apply.
