### ISSUE TITLE
Plugin says that it can't find data, but it can.

### ISSUE THREAD

**Issue by blairdrummond** [IBM/argocd-vault-plugin#180]
**Describe the bug**
The plugin reports that it cannot find data in Vault at a specific path, but it *does* find it, it just doesn't handle it properly. This snippet is the culprit.

https://github.com/IBM/argocd-vault-plugin/blob/24ef24ec85f9f9a0d802ba86dc0a3ffff42eb854/pkg/backends/vault.go#L54-L62

**To Reproduce**

As is, using this configmap.yaml

```yaml
# argocd@argocd-repo-server-6bd8b8fccc-q9msq:~$ cat /tmp/conf2.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: default
  annotations:
    avp.kubernetes.io/path: "argocd/my-secret"
data:
  secret: <my-value>
```

Running the plugin, I get 

```
argocd@argocd-repo-server-6bd8b8fccc-q9msq:~$ /usr/local/bin/argocd-vault-plugin -s vault-configuration generate /tmp/conf2.yaml
(0x1abf200,0xc0005b0e00)Error: Could not get data from Vault, check that kv-v2 is the correct engine
Usage:
  argocd-vault-plugin generate <path> [flags]

Flags:
  -c, --config-path string   path to a file containing Vault configuration (YAML, JSON, envfile) to use
  -h, --help                 help for generate
  -s, --secret-name string   name of a Kubernetes Secret containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD)

Could not get data from Vault, check that kv-v2 is the correct engine
```

However the data **is** in Vault, the go code seems to just be selecting `"data"` from the secret, which is not valid in this scenario? After some good ol' `fmt.Println` debugging , if you change it to this, then you get

```golang
	if kvVersion == "2" {

		if len(secret.Data) == 0 {
			return nil, fmt.Errorf("The Vault path: %s is empty - did you forget to include /data/ in the Vault path for kv-v2?", path)
		}

		return secret.Data, nil

		// if _, ok := secret.Data["data"]; ok {
		// 	return secret.Data["data"].(map[string]interface{}), nil
		// }

		// fmt.Println(secret.Data)

		// return nil, errors.New("Could not get data from Vault, check that kv-v2 is the correct engine")
	}
```

```yaml
# compile the new binary and copy it into the pod
# argocd@argocd-repo-server-6bd8b8fccc-q9msq:~$ /tmp/plugin -s vault-configuration generate /tmp/conf2.yaml
(0x1ac46c0,0xc000334240)apiVersion: v1
data:
  secret: supersecret
kind: ConfigMap
metadata:
  annotations:
    avp.kubernetes.io/path: argocd/my-secret
  name: example-configmap
  namespace: default
---
```

**Expected behavior**

The plugin should find the existing keys, of course. I am curious why the `"data"` field is there in the first place? I have seen it mentioned in one or two places, but I have not seen it in effect? (I am new to Vault, though.)

**Additional context**

If it's helpful, my setup environment is here. (A little messy still, proof-of-concept), but the manifests and versions I deployed are there.

https://github.com/blairdrummond/vault-argocd-test

If it's useful, this is the [vault config](https://github.com/blairdrummond/vault-argocd-test/blob/db23ba5f6b8b6bf303b281703099f60821381cf2/Makefile#L29-L71)

**Comment by werne2j** [comment]
Hi @blairdrummond. The `data` field is there because that is how the Vault KV V2 (https://www.vaultproject.io/api-docs/secret/kv/kv-v1#read-secret) response is structured. Where as the KV V1 (https://www.vaultproject.io/api-docs/secret/kv/kv-v1#read-secret) does not have that nested data field. Looks at the responses, you will be able to see the difference.

So what does that mean for your issue? Well, KV V2 is the default secret engine but it appears as though your Vault path is KV V1. So you can just set the `avp.kubernetes.io/kv-version` annotation to be V1 which will bypass the nested data. For example:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-configmap
  namespace: default
  annotations:
    avp.kubernetes.io/path: "argocd/my-secret"
    avp.kubernetes.io/kv-version: "1"
data:
  secret: <my-value>
```
This line https://github.com/IBM/argocd-vault-plugin/blob/main/pkg/backends/vault.go#L64 should help you understand what setting `kv-version` to `1` will do.

Hope that helps
