### ISSUE TITLE
Support for jsonnet

### ISSUE THREAD

**Issue by vediatoni** [IBM/argocd-vault-plugin#181]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
ArgoCD supports jsonnet. If possible can you consider adding jsonnet support to this plugin?

**Describe alternatives you've considered**
For now I'll just stay with Helm

**Additional context**
https://argoproj.github.io/argo-cd/user-guide/jsonnet/

**Comment by werne2j** [comment]
@vediatoni As of this moment, if you are generating yaml files such as https://github.com/google/jsonnet/blob/master/case_studies/kubernetes/example.jsonnet then AVP can be used. You would create a configManagementPlugins like with helm (this is not a real solution, just an idea of what is possible):
```
configManagementPlugins: |
  - name: argocd-vault-plugin-helm
    generate:
      command: ["sh", "-c"]
      args: ["jsonnet -o all.yaml . && argocd-vault-plugin generate all.yaml"]
```
However, if your jsonnet is generating json, that is not supported at this time. So we would need to add that into the codebase.
