### ISSUE TITLE
Manifest generation error (cached): sh -c helm dependency build failed

### ISSUE THREAD

**Issue by tuananh** [IBM/argocd-vault-plugin#190]
**Describe the bug**
I got the following error when creating app that build with argocd-vault-plugin-helm

If i change the app crd to use helm, it works. im not sure if this is argocd-related or vault-plugin related ?

```
rpc error: code = Unknown desc = Manifest generation error (cached): sh -c helm dependency build failed exit status 1: Error: no cached repository for helm-manager-e46a8f287f04319425669077b21ddbb03728437d622ca20249691b2144d7d79d found. (try 'helm repo update'): open /.cache/helm/repository/helm-manager-e46a8f287f04319425669077b21ddbb03728437d622ca20249691b2144d7d79d-index.yaml: no such file or directory
```

**To Reproduce**
i have `Chart.yaml`

```yaml
apiVersion: v2
name: app-vault-example
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: hello-helm
  version: 0.1.2
  repository: https://<private-repo>
```
and `values.yaml` for chart values.

The app crd is like this

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-example
  annotations:
    argocd-image-updater.argoproj.io/image-list: myimage=<registry-url>/hello-nodejs:1.x
    argocd-image-updater.argoproj.io/myimage.helm.image-name: hello-helm.image.repository
    argocd-image-updater.argoproj.io/myimage.helm.image-tag: hello-helm.image.tag
    argocd-image-updater.argoproj.io/myimage.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/gitlab-creds
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/myimage.force-update: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://<my-gitlab-repo-workload>'
    path: app-vault-example
    targetRevision: master
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_args
          value: -f values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-demo
  syncPolicy:
    automated: {}
```

**Expected behavior**

should be able to sync

**Screenshots**

**Additional context**

Im using argocd operator with openshift. argocd version 2.0.5

**Comment by tuananh** [comment]
When i change it to helm, it works fine

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-example
  annotations:
    argocd-image-updater.argoproj.io/image-list: myimage=<registry-url>/hello-nodejs:1.x
    argocd-image-updater.argoproj.io/myimage.helm.image-name: hello-helm.image.repository
    argocd-image-updater.argoproj.io/myimage.helm.image-tag: hello-helm.image.tag
    argocd-image-updater.argoproj.io/myimage.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/gitlab-creds
    argocd-image-updater.argoproj.io/git-branch: master
    argocd-image-updater.argoproj.io/myimage.force-update: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://<my-gitlab-repo-workload>'
    path: app-vault-example
    targetRevision: master
    helm:
       valueFiles:
         - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd-demo
  syncPolicy:
    automated: {}
```
