### ISSUE TITLE
AWS Secrets Manager backend: version validation error

### ISSUE THREAD

**Issue by jakubigla** [IBM/argocd-vault-plugin#199]
**Describe the bug**
I'm getting the following error when trying to execute the plugin against the awssecretsmanager backend:
```
Error: InvalidParameter: 1 validation error(s) found.
- minimum field size of 32, GetSecretValueInput.VersionId.
```

**To Reproduce**
1. Set environmental variables:
    ```
    export AWS_REGION=eu-central-1 
    export export AVP_TYPE=awssecretsmanager
    ```
2. Make sure local credentials are set up and are working (for instance `aws secretsmanager list-secrets`)
3. Add secret to the AWS Secrets Manager in `eu-central-1` region:
    name: test-secret
    key/value: test-key/test-val
4. Create secret file with the following content:
    ```
    apiVersion: v1
    kind: Secret
    metadata:
      name: my-secret
      annotations:
        avp.kubernetes.io/path: "test-secret"
    stringData:
      url: git@gitlab.com:getindata/streaming-labs
      test: <test-key>
    type: Opaque
    ```
5. Run `argocd-vault-plugin generate secret.yml`

**Expected behavior**
The plugin behaves as described in a backend section in the documentation.
