### ISSUE TITLE
Allow importing all secrets from a KV secret into a secret.

### ISSUE THREAD

**Issue by AndresPineros** [IBM/argocd-vault-plugin#208]
**Is your feature request related to a problem? Please describe.**
It is a little annoying to add new "key: vault-key" to the Kubernetes Secret(s) whenever we add a new path to a Vault secret.
It means creating a new Helm Chart version and testing it across the environments just so that a new secret can be added to the Secret and consumed by the app. I don't feel like new versions of the infrastructure should be created just because a new secret arrived to Vault.

**Describe the solution you'd like**
Simply allow creating a secret with an annotation that allows importing all keys from the Vault secret into the Secret.

Something like:
```
apiVersion: v1
kind: Secret
metadata:
  name: something
  annotations:
    avp.kubernetes.io/import-all-path: secrets/mykv/mysecret
data:
  placeholder: placeholder #not sure if this placeholder is necessary or we can work with empty data.
```

If the Vault secret has the key values:
```
username: myuser
password: mypassword
```

then the rendered Kubernetes Secret would be:
```
apiVersion: v1
kind: Secret
metadata:
  name: something
data:
  username: myuser
  password: mypassword
```
This also enforces a one-to-one relation between the Vault secrets and the app secret variables, which I think makes everything much clearer for people who want to debug issues with the secrets. They don't need to read resources to understand which vault secret is mapped to which secret key. Everything is more straight-forward. Obviously, the one-to-one mapping depends on the use-case and structure of Vault for each project, so I propose an alternative below in case someone wants a partial mapping.

**Describe alternatives you've considered**
Maybe if we don't want all the Secret keys to be mapped to the Vault keys, we could override or add extra keys. So with the example from above, we could do something like:

```
apiVersion: v1
kind: Secret
metadata:
  name: something
  annotations:
    avp.kubernetes.io/import-all-path: secrets/mykv/mysecret
data:
  passWORD: <password>
  extraKey: myExtraKeySecret
```
which would result in the secret:
```
apiVersion: v1
kind: Secret
metadata:
  name: something
data:
  username: myuser
  passWORD: mypassword
  extraKey: myExtraKeySecret
```
