### ISSUE TITLE
Secrets loaded from the gcpsecretmanager backend are always base64 encoded

### ISSUE THREAD

**Issue by ian-thebridge-lucidworks** [IBM/argocd-vault-plugin#213]
**Describe the bug**
I am trying to load an IP address from a secret in GCP secretmanager into the `spec.nfs.server` field of a   `PersistentVolume` resource. The template always renders with the value base 64 encoded instead of using the value stored in gcpsecretmanager as is. 

Version of argocd-vault-plugin: v1.4.0

**To Reproduce**

- Create a secret in GCP Secret Manager called plugin-test with a secret version with value: `1.2.3.4`
- create a pv from the below template, filling out your `gcp_project`
```
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume
spec:
  capacity:
    storage: "30Gb"
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/path"
    server:  "<path:projects/${gcp_project}/secrets/plugin-test#plugin-test>"
```
- create a `config.yaml` file with the following contents:
```
---
AVP_TYPE: gcpsecretmanager
```
- run `./argocd-vault-plugin generate pv.yaml -c config.yaml`
- This generates:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 30Gb
  nfs:
    path: /path
    server: MS4yLjMuNA==
---
```

I would expect the `spec.nfs.server` field to contain `1.2.3.4`, instead it contains `MS4yLjMuNA==`
