### ISSUE TITLE
Add a new modifier to process non-string replacement data

### ISSUE THREAD

**Issue by teejaded** [IBM/argocd-vault-plugin#214]
**Is your feature request related to a problem? Please describe.**
I have significant amount data that is stored in json, in Vault.  I don't think it is currently possible to isolate specific sub-values in this case.

Consider the following test secret:
![Screen Shot 2021-10-14 at 4 37 44 PM](https://user-images.githubusercontent.com/3037973/137409668-fb24f8e7-395b-4c9f-8da5-7e8c71ecabc7.png)

If I need to isolate value of `.credentials.user` there's no way to do this currently.

**Describe the solution you'd like**

Add a new modifier that will allow us to select sub-sets of data possibly via jsonpath.

**Describe alternatives you've considered**
Duplicating data inside vault for use only with AVP.  This, for me, is sub-optimal since it would require additional automation or a manual process.

**Comment by teejaded** [comment]
Okay, updated.
In the updated PR to add a modifier you just write a new function with the correct signature and add it into the map.

```golang
var modifiers = map[string]func([]string, interface{}) error{
	"base64encode": base64encode,
	"jsonPath":     jsonPath,
}
```

Now we can easily add new modifiers and pipe them together.

```
./bin/test-avp-path.sh '<path:secret/devops/test#credentials | jsonPath .pass | base64encode>' 'avp.kubernetes.io/kv-version: "1"'
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/kv-version: "1"
  name: test
stringData:
  testpath: bXlwYXNz
---
```

Wrote a quick `fromJSON` for fun.  I'm not sure if it's actually useful so I didn't commit it.

```
./bin/test-avp-path.sh '<path:secret/devops/test#embeddedJson>' 'avp.kubernetes.io/kv-version: "1"'
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/kv-version: "1"
  name: test
stringData:
  testpath: '{"key": "value"}'
  
./bin/test-avp-path.sh '<path:secret/devops/test#embeddedJson | fromJSON | jsonPath .key>' 'avp.kubernetes.io/kv-version: "1"'
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp.kubernetes.io/kv-version: "1"
  name: test
stringData:
  testpath: value
---
```
