### ISSUE TITLE
Error "Error: AVP_ROLE_ID and AVP_SECRET_ID for approle authentication cannot be empty Usage: argocd-vault-plugin generate" Passing Env from the manifest in the argocd application

### ISSUE THREAD

**Issue by jaipalkomakula** [IBM/argocd-vault-plugin#225]
**Describe the bug**

We are trying to passing env from the argocd application, below is the example of the application manifest. 

project: default
source:
  repoURL: 'https://github.com/jaipalkomakula/arogcd-vault-plugin-demo.git'
  path: vault
  targetRevision: HEAD
  plugin:
    name: argocd-vault-plugin
    env:
      - name: AVP_AUTH_TYPE
        value: approle
      - name: AVP_ROLE_ID
        value: xxxxxxxx
      - name: AVP_SECRET_ID
        vaule: xxxxxxxx
      - name: VAULT_ADDR
        value: 'https://or.vault.example.com'
      - name: AVP_TYPE
        value: vault
      - name: AVP_KV_VERSION
        value: "1"
destination:
  server: 'https://kubernetes.default.svc'
  namespace: argocd-vault3
syncPolicy: {}

Where the argocd is running:
The Argocd instant on the Opnshift 4.7 and build with the argocd operator
 
We used latest argocd vault plugin v1.5.0 and latest argocd image

Error: 

Unable to save changes: application spec for argocd-vault is invalid: InvalidSpecError: Unable to generate manifests in vault: rpc error: code = Unknown desc = `argocd-vault-plugin generate ./` failed exit status 1: Error: AVP_ROLE_ID and AVP_SECRET_ID for approle authentication cannot be empty Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD)

argocd-vault-plugin version
argocd-vault-plugin v1.5.0 (89e02217591d856e3902be247df36ec7d489270f) BuildDate: 2021-11-01T15:53:36Z

Some one please let us know why we could able to pass the env from application level instated of crated the secrets and passing as an env in to the pod ?

**Comment by jkayani** [comment]
```
env:
- name: AVP_AUTH_TYPE
value: approle
- name: AVP_ROLE_ID
value: xxxxxxxx
- name: AVP_SECRET_ID
vaule: xxxxxxxx
- name: VAULT_ADDR
```

> - name: AVP_SECRET_ID
vaule: xxxxxxxx

Maybe you misspelled `value` for the `AVP_SECRET_ID` block? 

I tested this scenario locally (which I don't recommend actually doing since you're putting Vault credentials in the Argo app spec directly) and it worked fine:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-nginx
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc 
  project: default
  source:
    repoURL: 'https://github.com/jkayani/avp-demo-kubecon-2021'
    targetRevision: HEAD
    path: apps/git/nginx/manifests

    # We're telling Argo CD to use our plugin to deploy the manifests
    plugin:
      name: argocd-vault
      env:
        - name: AVP_AUTH_TYPE
          value: approle
        - name: AVP_ROLE_ID
          value: ???
        - name: AVP_SECRET_ID
          value: ???
```

in the `argocd-repo-server`:

```
... some stuff
      containers:
      - name: argocd-repo-server

        volumeMounts:
        - name: custom-tools
          subPath: argocd-vault-plugin
          mountPath: /usr/local/bin/argocd-vault-plugin

        # Configure AVP
        env:
          - name: AVP_TYPE
            value: vault
          - name: VAULT_ADDR
            value: http://vault:8200
... more stuff
