### ISSUE TITLE
Add vault path as annotation 

### ISSUE THREAD

**Issue by werne2j** [IBM/argocd-vault-plugin#23]
We need to add the logic to handle a path as an annotation in in resource

```
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    path: "path/to/vault"
```
