### ISSUE TITLE
Ability to use multiple secrets?

### ISSUE THREAD

**Issue by flickerfly** [IBM/argocd-vault-plugin#230]
If I have a set of secrets with container registry credentials to pull the images from and another secret with application secrets, say database credentials, can I pull them from different places within Vault using this plugin?

**Comment by werne2j** [comment]
@flickerfly Yes, this is related to the multi tenancy strategy. In order to pull from different Vaults, you would need to do one of a couple different strategies.

You could use the Kubernetes Config strategy (https://ibm.github.io/argocd-vault-plugin/v1.5.0/config/#kubernetes-secret) And then have multiple secrets in the same namespace as your Argo CD. This way you could then create multiple config management plugins that use AVP but each have there own set of credentials. So you could pull from different vaults.

The other option is to put your AVP config in the Argo CD Application CR. You would have an Application where you specify the VAULT_ADDR, AVP_TYPE, etc
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-application-name
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_TYPE
           value: vault
        - name: VAULT_ADDR
           value: http://vault:8200
        - name: AVP_AUTH_TYPE
           value: k8s
        - name: AVP_K8S_ROLE
           value: argocd
    repoURL: http://your-repo/
    targetRevision: HEAD
  project: default
```

Hopefully that helps
