### ISSUE TITLE
Failing to use a Base64 encoded .dockerconfigjson from Google Secret Manager

### ISSUE THREAD

**Issue by MoskitoHero** [IBM/argocd-vault-plugin#239]
**Describe the bug**
When I try to use a base64-encoded string as a `.dockerconfigjson` in 'data` in a `kubernetes.io/dockerconfigjson` secret in a Helm chart, the plugin fails to decode the Data. I am using Google Secret Manager.
I have triple-checked that my base64 data can be decoded.

**To Reproduce**
1. Encode a docker json config with base64
2. Save it in Google Secret Manager
3. Check it decodes as expected
```sh
gcloud secrets versions access 7 --secret=gitlab-docker-registry-credentials-64 | base64 -d
{
  "auths": {
    "registry.gitlab.com": {
      "auth": "................................................................" // Correct auth string
    }
}
```
4. Use it in a Secret in the `data` entry
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <path:{{ .Values.googleSecretManager.path }}/{{ .Values.googleSecretManager.ids.gitlabDockerRegistryCredentials64 }}>
```
5. Push and watch it fail to generate the secret with
```
Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...|-64\u003e"},"kind":"|..., bigger context ...|crets/gitlab-docker-registry-credentials-64\u003e"},"kind":"Secret","metadata":{"labels":{"app.kuber|...
```

**Expected behavior**
The `regcred` secret should be created.

**Comment by werne2j** [comment]
@MoskitoHero I was not able to recreate this issue. To me it looks like there is no replacement happening `|crets/gitlab-docker-registry-credentials-64\u003e"}` so you're actually not providing base64 to kubernetes. I would double check to make sure your AVP setup is correct and the replacement is actually happening.

**Comment by MoskitoHero** [comment]
Thank you for your reply.

`crets` seems to be the truncated end of `secret`. What I was experiencing was related to https://github.com/IBM/argocd-vault-plugin/issues/238 

So I have updated `.dockerconfigjson` to look like `<path:{{ .Values.googleSecretManager.path }}/{{ .Values.googleSecretManager.ids.gitlabDockerRegistryCredentials64 }}#{{ .Values.googleSecretManager.ids.gitlabDockerRegistryCredentials64 }}>`

So now I get the actual data from the server. However, all my are base64-encoded twice. What am I doing wrong now?

The command for the plugin is defined in the configmap like this:
```yaml
  configManagementPlugins: |-
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
    - name: argocd-vault-plugin-helm
      init:
        command: [sh, -c]
        args: ["helm dependency build"]
      generate:
        command: ["sh", "-c"]
        args: ["helm template $ARGOCD_APP_NAME ${helm_args} . > all.yaml && argocd-vault-plugin generate all.yaml"]

```
and used like this:
```yaml
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_args
          value: -f values.yaml
```
