### ISSUE TITLE
Vault kv2 secret versioning support

### ISSUE THREAD

**Issue by ls-devon-hakel-kinko** [IBM/argocd-vault-plugin#58]
Does this plugin support [vault secret versioning](https://learn.hashicorp.com/tutorials/vault/versioned-kv)?
If not, do you plan on supporting it in the future?

Example:
```
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    vault_secret_version: '5'  # ability to specify secret revision
    avp_path: "path/to/secret"
type: Opaque
data:
  password: <password-vault-key>

```
