### ISSUE TITLE
Unnecessary panics over non map/string list elements

### ISSUE THREAD

**Issue by jkayani** [IBM/argocd-vault-plugin#63]
**Describe the bug**

Given a YAML like this:

```
apiVersion: v1
kind: Secret
metadata:
  name: a-secret
  annotations:
    avp_path: secret/data/my-app/regsecret
    kv_version: "2"
type: Opaque
data:
  CONTRIVED_EXAMPLE:
    - 1
    - 2
```

the plugin will panic like this:

```
panic: Deserialized YAML list node is non map[string]interface{} nor string

goroutine 1 [running]:
github.com/IBM/argocd-vault-plugin/pkg/kube.replaceableInner(0xc000120108, 0xc000120108)
... stacktrace
```

The reason is because of the way list elements are handled in `replacableInner()` and `replaceInner()`. 

**To Reproduce**
See above

**Expected behavior**

The proper behavior should just be to skip over non-string, non-map, non-list elements since those are ineligible for containing `<placeholder>`'s since they are non-strings. For string, map, and list elements that appear in a _list_, we should check for `<placeholder>`'s. 

**Screenshots**

**Additional context**
