### ISSUE TITLE
Shouldn't "secretData" be named "stringData" according to Kubernetes Secrets?

### ISSUE THREAD

**Issue by sam-sla** [IBM/argocd-vault-plugin#69]
**Describe the bug**
At first I thought it was not a bug because the replace works when testing inside the pod, but then k8s actually tries to parse the secret it fails because it doesn't recognize "secretData". The naming looks to be incorrect and doesn't match the api `stringData` https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#secretlist-v1-core

**Steps to reproduce**
Create a secret with secretData to be replaced as-is (for example with a json object):

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp_path: "avp/data/test"
type: Opaque
secretData:
  credentials.json:
    <sample>
```

Note that it works for the actual replace, as tested inside the pod:
```
argocd@argocd-repo-server-7c4cf688fd-nxxjk:~$ argocd-vault-plugin generate process/ -s argocd-vault-plugin-credentials
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp_path: avp/data/test
  name: example-secret
secretData:
  credentials.json: |
    {
      "user": "secret",
      "pass": "secret",
      "extra_secret": "secret"
    }
type: Opaque
```

But then the secret object fails to be parsed by k8s
![image](https://user-images.githubusercontent.com/19795751/108987463-9ced4e80-7693-11eb-8d0a-5fd9215d5a32.png)

**Expected behavior**
When passing string data to be emitted as-is we should use the field `stringData`, but the plugin handles it for a field named `secretData`. I expect that simply renaming the field will fix this problem.
