### ISSUE TITLE
How to use plugin with kustomize

### ISSUE THREAD

**Issue by antonionappi88** [IBM/argocd-vault-plugin#74]
Hello,
I'm new to ArgoCD and I'm facing a strange issue.

I'm using a custom plugin to get secret from Vault and produce a K8s secret.

This is my application:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-self
  namespace: argocd
  labels:
    app: prometheus
    component: self
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: overlays/qa/clusters/my-cluster
    repoURL: https://myrepo.com
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
 ```
 In my repository at path `overlays/qa/clusters/my-cluster` I have: 

```bash
├── kustomization.yaml
├── patches
│   ├── alertmanager_patch.yaml
│   ├── grafana_patch.yaml
│   ├── ingress_controller_patch.yaml
│   ├── prometheus_operator_patch.yaml
│   └── pushgateway_patch.yaml
├── remote_secrets
│   └── my_secret.yaml
├── self.yaml
```

and this is my kustomation.yaml

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/prometheus
- ./remote_secrets/my_secret.yaml
- ./self.yaml
```

If I use the plugin in my application, it isn't able to create other resource then `./remote_secrets/my_secret.yaml`.

If instead I don't specify the plugin and let kustomize to work, the secret isn't update with the value from Vault.

Is this a bug or is it suppose to work like that ?

Thanks,
Antonio

**Comment by werne2j** [comment]
Hi @animeshsingh, so the reason this wouldn't work is most likely that `./remote_secrets/my_secret.yaml` is the only valid kubernetes resource. That being said, you can get the plugin to work with kustomize. What you would do is, add a new `configManagementPlugin` that first runs `kustomize build` and pipes that to the plugin. For example:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: argocd-vault-plugin-kustomize
      generate:
        command: [sh, -c]
        args: ["kustomize build . > all.yaml && argocd-vault-plugin generate all.yaml"]
```
This would run kustomize, output to a single file and then run the argocd-vault-plugin on that file.

Hope that helps!

**Comment by werne2j** [comment]
This PR adds the kustomize example https://github.com/IBM/argocd-vault-plugin/pull/77

**Comment by antonionappi88** [comment]
Hi Jacob,
thanks a lot! This fixed the issue. Only one minor change. 

The double quote in the command are needed.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: argocd-vault-plugin-kustomize
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build . > all.yaml && argocd-vault-plugin generate all.yaml"]
```

Thanks a lot again!
