### ISSUE TITLE
Allow path to secret to be secret key specific

### ISSUE THREAD

**Issue by werne2j** [IBM/argocd-vault-plugin#84]
We should allow specifying a path to a secret on a key by key basis. This would add support to anyone that use the one key per secret model. We can discuss the actual syntax but something like..
```
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
data:
  sample-secret: <path:path/to/secret#key-name>
type: Opaque
```
