### ISSUE TITLE
Support to Read Base64 format and Decode it in Secret - for storing Certificates

### ISSUE THREAD

**Issue by adit0012m** [IBM/argocd-vault-plugin#95]
@jkayani I should Thank everyone for the wonderful work.

We are expecting something similar. Describing few challenges as per my understanding and testing.

Tested the for both use cases,
```data:
          THING: <mykey>
``` 
The plugin does replace `data` key from Vault as-is ( but, Ref: then the plugin will base64 the Vault data before replacing the placeholder..). In our case, not the correct behaviour then.
and
```stringData:
          THING: <mykey>
```
Expected `stringData` inside the key should replace value from Vault as-is which is not working.

Configured yaml file looks as below:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  annotations:
    avp_path: <kv/data/secret-folder>
type: Opaque
data:
  MyKey: <MyKey>
```
Thoughts on this.

**Expecting a new Feature or an Existing Options are not Aware**
The plugin works perfectly fine with the plain text stored in Vault get's the value back in to the secret. Is there a way we can decode values present in a Vault secret path are encoded in the `base64` format at the secret end. This helps us to store certificate formats such as .crt, .pem etc...

* Store certificates in `base64` encoded format in Vault secret path and values are decoded when retrieves it from Vault server. Just to give an example. Same is achieved using Consul Template to render the Vault secret with side car container Vault k8s auth method.

Ex: ```{{with secret "secret/example"}} MyKey = {{.Data.data.MyKeyCerts | base64Decode}}{{end}}

So, is there any way we can decode base64 format data before it replaces the placeholder with the actual value --> something like  `"<base64decode MyKey>".`

_Originally posted by @adit0012m in https://github.com/IBM/argocd-vault-plugin/issues/92#issuecomment-797723761_

**Comment by werne2j** [comment]
@adit0012m This is an interesting thought, we will look into if adding transformer helpers such as `base64decode` and `base64encode` make sense for the plugin. Thank you for your feature request!

**Comment by clcchai** [comment]
+1 we also have requirements to use vault to manage tls.crt and tls.key and would need the plugin to work with the above use case

**Comment by werne2j** [comment]
Once #96 gets merged, you will be able to load in a base64 encoded cert to vault and then use the data field to put into your cluster. 

For example:
In Github..
```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    avp_path: kv/data/test
  name: sample-cert
data:
  sample-cert: <sample-cert>
type: Opaque
```
In Vault..
<img width="953" alt="Screen Shot 2021-03-16 at 9 14 46 AM" src="https://user-images.githubusercontent.com/5973248/111314738-10053780-8638-11eb-84b5-e93376ab2559.png">
In Kubernetes..
<img width="592" alt="Screen Shot 2021-03-16 at 9 15 08 AM" src="https://user-images.githubusercontent.com/5973248/111314782-1bf0f980-8638-11eb-9aa9-03518a4da5ad.png">

Does that work for your use case?
